import React from "react";
import { Document, Page, Text, View, StyleSheet, pdf } from "@react-pdf/renderer";
import type { ScoreOutput } from "./audit.scorer";

const styles = StyleSheet.create({
  page: { padding: 30, fontFamily: "Helvetica" },
  title: { fontSize: 24, marginBottom: 6, color: "#1e3a5f" },
  subtitle: { fontSize: 12, color: "#666", marginBottom: 20 },
  scoreBox: { padding: 15, marginBottom: 15, borderRadius: 4 },
  scoreText: { fontSize: 36, fontWeight: "bold", color: "#fff" },
  scoreLabel: { fontSize: 14, color: "#fff", marginTop: 4 },
  section: { marginBottom: 15 },
  sectionTitle: { fontSize: 14, fontWeight: "bold", marginBottom: 8, color: "#1e3a5f" },
  row: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 4, borderBottomWidth: 1, borderBottomColor: "#eee" },
  catName: { fontSize: 11, color: "#333" },
  catScore: { fontSize: 11, color: "#666" },
  bar: { height: 6, backgroundColor: "#e0e0e0", borderRadius: 3, marginTop: 2 },
  barFill: { height: 6, borderRadius: 3 },
  footer: { fontSize: 9, color: "#999", textAlign: "center", marginTop: 30, borderTopWidth: 1, borderTopColor: "#eee", paddingTop: 10 },
  checklist: { marginBottom: 15 },
  checkRow: { flexDirection: "row", paddingVertical: 3, borderBottomWidth: 0.5, borderBottomColor: "#f0f0f0" },
  checkIcon: { width: 14, fontSize: 10, color: "#333" },
  checkLabel: { flex: 1, fontSize: 10, color: "#333" },
  checkStatus: { width: 50, fontSize: 9, textAlign: "right", color: "#666" },
});

const categoryLabels: Record<string, string> = {
  mobileScore: "Mobile Responsiveness", speedScore: "Page Load Speed", seoScore: "SEO Basics",
  contentScore: "Content Freshness", socialScore: "Social Media Activity",
  pricingScore: "Pricing Visibility", paymentScore: "Online Payment",
  aiScore: "AI / Chatbot", trustScore: "Trust Signals", contactScore: "Contact Visibility",
  preLaunchScore: "Pre-Launch Readiness",
};

function AuditPDF({ url, score }: { url: string; score: ScoreOutput }) {
  const levelColor = score.totalScore <= 25 ? "#ef4444" : score.totalScore <= 50 ? "#f97316" : score.totalScore <= 75 ? "#eab308" : "#22c55e";
  const preLaunchLabels: Record<string, string> = {
    uniquePageTitles: "Unique Page Titles", metaDescriptions: "Meta Descriptions",
    socialShareImg: "Social Share Image", altTxtOnImages: "Alt Text on Images",
    localSchema: "Local Schema Markup", internalLinks: "Internal Links",
    robotsTxt: "Robots.txt", ctaAboveFold: "CTA Above the Fold",
    stickyMobileCta: "Sticky Mobile CTA", faqs: "FAQ Section",
    responseTimePromise: "Response Time Promise", breadcrumbs: "Breadcrumbs",
    custom404: "Custom 404 Page", thankYouPage: "Thank You Page",
    realReviews: "Real Reviews", caseStudies: "Case Studies",
    teamPhoto: "Team Photo", mapsDirections: "Maps & Directions",
    privacyPolicy: "Privacy Policy", googleAnalytics: "Google Analytics",
  };
  const preLaunchChecks = (score as ScoreOutput & { preLaunchChecks?: Record<string, boolean> }).preLaunchChecks;
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>Ghost Audit Report</Text>
        <Text style={styles.subtitle}>Wujood — Digital Presence Audit for {url}</Text>
        <View style={[styles.scoreBox, { backgroundColor: levelColor }]}>
          <Text style={styles.scoreText}>{score.totalScore}/110</Text>
          <Text style={styles.scoreLabel}>{score.ghostLabel.en}</Text>
        </View>
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Category Breakdown</Text>
          {Object.entries(score.categories).map(([key, val]) => (
            <View key={key} style={styles.row}>
              <View style={{ flex: 1 }}>
                <Text style={styles.catName}>{categoryLabels[key] || key}</Text>
                <View style={styles.bar}>
                  <View style={[styles.barFill, { width: `${val * 10}%`, backgroundColor: levelColor }]} />
                </View>
              </View>
              <Text style={styles.catScore}>{val}/10</Text>
            </View>
          ))}
        </View>
        {preLaunchChecks && (
          <View style={styles.checklist}>
            <Text style={styles.sectionTitle}>Pre-Launch Checklist (20 Items)</Text>
            {Object.entries(preLaunchLabels).map(([key, label]) => (
              <View key={key} style={styles.checkRow}>
                <Text style={styles.checkIcon}>{preLaunchChecks[key] ? "✓" : "✗"}</Text>
                <Text style={styles.checkLabel}>{label}</Text>
                <Text style={styles.checkStatus}>{preLaunchChecks[key] ? "Pass" : "Missing"}</Text>
              </View>
            ))}
          </View>
        )}
        <Text style={styles.footer}>Generated by Wujood (wujood.vercel.app) — From Digital Ghost to Digital Presence</Text>
      </Page>
    </Document>
  );
}

export async function generatePdf(url: string, score: ScoreOutput): Promise<Blob> {
  return await pdf(<AuditPDF url={url} score={score} />).toBlob();
}
